In [2]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv("/Breast_cancer_data.csv",na_values=[np.nan,'na',"NA",'n/a',"N/A","--","-"])

In [6]:
data

mean_radius  mean_texture  ...  mean_smoothness  diagnosis
0          17.99         10.38  ...          0.11840          0
1          20.57         17.77  ...          0.08474          0
2          19.69         21.25  ...          0.10960          0
3          11.42         20.38  ...          0.14250          0
4          20.29         14.34  ...          0.10030          0
..           ...           ...  ...              ...        ...
564        21.56         22.39  ...          0.11100          0
565        20.13         28.25  ...          0.09780          0
566        16.60         28.08  ...          0.08455          0
567        20.60         29.33  ...          0.11780          0
568         7.76         24.54  ...          0.05263          1

[569 rows x 6 columns]

In [9]:
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [10]:
X

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
0          17.99         10.38          122.80     1001.0          0.11840
1          20.57         17.77          132.90     1326.0          0.08474
2          19.69         21.25          130.00     1203.0          0.10960
3          11.42         20.38           77.58      386.1          0.14250
4          20.29         14.34          135.10     1297.0          0.10030
..           ...           ...             ...        ...              ...
564        21.56         22.39          142.00     1479.0          0.11100
565        20.13         28.25          131.20     1261.0          0.09780
566        16.60         28.08          108.30      858.1          0.08455
567        20.60         29.33          140.10     1265.0          0.11780
568         7.76         24.54           47.92      181.0          0.05263

[569 rows x 5 columns]

In [11]:
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: diagnosis, Length: 569, dtype: int64

In [12]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   mean_radius      569 non-null    float64
 1   mean_texture     569 non-null    float64
 2   mean_perimeter   569 non-null    float64
 3   mean_area        569 non-null    float64
 4   mean_smoothness  569 non-null    float64
dtypes: float64(5)
memory usage: 22.4 KB


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.225,random_state=1,stratify=y)

In [14]:
X_train

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
516        18.31         20.58          120.80     1052.0          0.10680
253        17.30         17.08          113.00      928.2          0.10080
215        13.86         16.93           90.96      578.9          0.10260
512        13.40         20.52           88.64      556.7          0.11060
105        13.11         15.56           87.21      530.2          0.13980
..           ...           ...             ...        ...              ...
509        15.46         23.95          103.80      731.3          0.11830
201        17.54         19.32          115.10      951.6          0.08968
92         13.27         14.76           84.74      551.7          0.07355
89         14.64         15.24           95.77      651.9          0.11320
161        19.19         15.94          126.30     1157.0          0.08694

[440 rows x 5 columns]

In [15]:
X_test

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
112        14.26         19.65           97.83      629.9          0.07837
371        15.19         13.21           97.65      711.8          0.07963
299        10.51         23.09           66.85      334.2          0.10150
231        11.32         27.08           71.76      395.7          0.06883
477        13.90         16.62           88.97      599.4          0.06828
..           ...           ...             ...        ...              ...
256        19.55         28.77          133.60     1207.0          0.09260
91         15.37         22.76          100.20      728.2          0.09200
437        14.04         15.98           89.78      611.2          0.08458
270        14.29         16.82           90.30      632.6          0.06429
272        21.75         20.99          147.30     1491.0          0.09401

[129 rows x 5 columns]

In [16]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [18]:
# pickling the model
import pickle
pickle_out = open("stdsc.pkl", "wb")
pickle.dump(sc_X, pickle_out)

pickle_out.close()


In [19]:
#Fitting MLPClassifier
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(random_state=1, max_iter=500).fit(X_train, y_train)

In [21]:
y_pred=clf.predict(X_test)

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94        48
           1       0.96      0.96      0.96        81

    accuracy                           0.95       129
   macro avg       0.95      0.95      0.95       129
weighted avg       0.95      0.95      0.95       129



In [23]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[45,  3],
       [ 3, 78]])

In [24]:
# pickling the model
import pickle
pickle_out = open("clf_cancer.pkl", "wb")
pickle.dump(clf, pickle_out)

pickle_out.close()


array([0])

array([[7.760e+00, 2.454e+01, 4.792e+01, 1.810e+02, 5.263e-02]])

array([1])

array([0])